const GAMES = [
  {
    id: 1,
    name: "PUBG Mobile",
    dev: "Krafton Inc.",
    cat: "action",
    catLabel: "أكشن",
    icon: "🎯",
    color: "#c8a951",
    bg: "linear-gradient(135deg, #1a1a2e 0%, #c8a951 100%)",
    rating: 4.3,
    downloads: "100م+",
    size: "1.2 GB",
    android: "6.0+",
    featured: true,
    tags: ["باتل رويال", "إطلاق نار", "متعدد اللاعبين"],
    desc: "العب مع أصدقائك في المعركة الأكثر إثارة! استمتع بتجربة بقاء لا مثيل لها مع رسومات مذهلة وأسلحة متنوعة. انزل في جزيرة مجهولة مع 100 لاعب وكن الأخير على قيد الحياة.",
    screenshots: ["🏝️", "🔫", "🎮", "🏆"]
  },
  {
    id: 2,
    name: "Clash of Clans",
    dev: "Supercell",
    cat: "strategy",
    catLabel: "استراتيجية",
    icon: "⚔️",
    color: "#e67e22",
    bg: "linear-gradient(135deg, #2c3e50 0%, #e67e22 100%)",
    rating: 4.6,
    downloads: "500م+",
    size: "320 MB",
    android: "5.0+",
    featured: true,
    tags: ["بناء", "حروب", "قبائل"],
    desc: "ابنِ قريتك، درّب جيشك، وخض حروب عشائر ملحمية! العب مع الملايين من اللاعبين حول العالم وأثبت أنك الأقوى.",
    screenshots: ["🏰", "⚔️", "💎", "🛡️"]
  },
  {
    id: 3,
    name: "Subway Surfers",
    dev: "Kiloo",
    cat: "adventure",
    catLabel: "مغامرة",
    icon: "🏃",
    color: "#9b59b6",
    bg: "linear-gradient(135deg, #6c3483 0%, #f39c12 100%)",
    rating: 4.5,
    downloads: "1ب+",
    size: "165 MB",
    android: "4.4+",
    featured: true,
    tags: ["جري لا نهائي", "مغامرة", "مجاني"],
    desc: "اركض بسرعة في مدن مختلفة حول العالم! تجنب العوائق واجمع العملات وافتح شخصيات جديدة. لعبة بسيطة ومسلية لا تمل منها.",
    screenshots: ["🏃", "🚇", "💰", "🎿"]
  },
  {
    id: 4,
    name: "FIFA Mobile",
    dev: "EA Sports",
    cat: "sports",
    catLabel: "رياضة",
    icon: "⚽",
    color: "#27ae60",
    bg: "linear-gradient(135deg, #1e3c72 0%, #2a9d8f 100%)",
    rating: 4.2,
    downloads: "50م+",
    size: "890 MB",
    android: "5.0+",
    featured: false,
    tags: ["كرة قدم", "رياضة", "بطولات"],
    desc: "العب كرة القدم مع أفضل اللاعبين في العالم! ابنِ فريقك المثالي، شارك في البطولات الحية، وكن بطل العالم.",
    screenshots: ["⚽", "🏟️", "🥅", "🏆"]
  },
  {
    id: 5,
    name: "Candy Crush Saga",
    dev: "King",
    cat: "puzzle",
    catLabel: "ألغاز",
    icon: "🍬",
    color: "#e91e8c",
    bg: "linear-gradient(135deg, #e91e8c 0%, #f39c12 100%)",
    rating: 4.4,
    downloads: "1ب+",
    size: "120 MB",
    android: "4.4+",
    featured: false,
    tags: ["ألغاز", "حلوى", "مستويات"],
    desc: "المباراة الكلاسيكية التي لا تقاوم! طابق الحلوى الملونة وتقدم عبر آلاف المستويات المثيرة. سهل التعلم، صعب الإتقان!",
    screenshots: ["🍬", "🍭", "⭐", "🎉"]
  },
  {
    id: 6,
    name: "Asphalt 9 Legends",
    dev: "Gameloft",
    cat: "racing",
    catLabel: "سباقات",
    icon: "🏎️",
    color: "#e74c3c",
    bg: "linear-gradient(135deg, #0f0c29 0%, #e74c3c 100%)",
    rating: 4.5,
    downloads: "100م+",
    size: "2.4 GB",
    android: "5.0+",
    featured: true,
    tags: ["سيارات", "سباقات", "ثلاثي الأبعاد"],
    desc: "سابق بأفضل سيارات العالم في مسارات مذهلة! استمتع بمطاردات مجنونة وحيل هوائية مثيرة برسومات على مستوى الكونسول.",
    screenshots: ["🏎️", "🛣️", "💨", "🏆"]
  },
  {
    id: 7,
    name: "Genshin Impact",
    dev: "miHoYo",
    cat: "rpg",
    catLabel: "RPG",
    icon: "⚡",
    color: "#3498db",
    bg: "linear-gradient(135deg, #1a1a2e 0%, #3498db 100%)",
    rating: 4.7,
    downloads: "10م+",
    size: "3.5 GB",
    android: "8.0+",
    featured: true,
    tags: ["RPG", "عالم مفتوح", "أنيمي"],
    desc: "استكشف عالم Teyvat الساحر! عش مغامرة ملحمية مع شخصيات فريدة ومعارك ديناميكية وقصة ملونة. تجربة AAA على الجوال.",
    screenshots: ["⚡", "🌸", "🗡️", "🐉"]
  },
  {
    id: 8,
    name: "Among Us",
    dev: "InnerSloth",
    cat: "action",
    catLabel: "أكشن",
    icon: "👨‍🚀",
    color: "#c0392b",
    bg: "linear-gradient(135deg, #0a0a0a 0%, #c0392b 100%)",
    rating: 4.1,
    downloads: "100م+",
    size: "50 MB",
    android: "6.0+",
    featured: false,
    tags: ["اجتماعي", "خيانة", "متعدد اللاعبين"],
    desc: "من هو الغريب؟ العب مع أصدقائك واكتشف الخائن قبل فوات الأوان! لعبة اجتماعية مثيرة تختبر مهارات التفكير والإقناع.",
    screenshots: ["👨‍🚀", "🚀", "🔪", "🗺️"]
  },
  {
    id: 9,
    name: "Mobile Legends",
    dev: "Moonton",
    cat: "action",
    catLabel: "أكشن",
    icon: "🧙",
    color: "#8e44ad",
    bg: "linear-gradient(135deg, #1a0533 0%, #8e44ad 100%)",
    rating: 4.3,
    downloads: "100م+",
    size: "540 MB",
    android: "4.4+",
    featured: false,
    tags: ["MOBA", "5v5", "أبطال"],
    desc: "أفضل لعبة MOBA للجوال! اختر بطلك، تعاون مع فريقك، وأسقط برج العدو. معارك عالية الكثافة في 10 دقائق.",
    screenshots: ["🧙", "⚔️", "🗡️", "🏰"]
  },
  {
    id: 10,
    name: "Minecraft",
    dev: "Mojang Studios",
    cat: "adventure",
    catLabel: "مغامرة",
    icon: "⛏️",
    color: "#7d5a00",
    bg: "linear-gradient(135deg, #74b9ff 0%, #2d3436 100%)",
    rating: 4.6,
    downloads: "10م+",
    size: "500 MB",
    android: "8.0+",
    featured: false,
    tags: ["بناء", "بقاء", "إبداع"],
    desc: "اصنع عالمك الخاص! ابنِ مجسمات ضخمة، اكتشف كهوفاً مجهولة، وانجُ من الليل. خيالك هو الحد الوحيد في هذا العالم البلوري.",
    screenshots: ["⛏️", "🏔️", "🌳", "🏗️"]
  },
  {
    id: 11,
    name: "Call of Duty Mobile",
    dev: "TiMi Studios",
    cat: "action",
    catLabel: "أكشن",
    icon: "💥",
    color: "#2c3e50",
    bg: "linear-gradient(135deg, #2c3e50 0%, #fd7272 100%)",
    rating: 4.4,
    downloads: "500م+",
    size: "1.8 GB",
    android: "5.1+",
    featured: false,
    tags: ["إطلاق نار", "باتل رويال", "متعدد"],
    desc: "تجربة Call of Duty الكاملة على جوالك! خوض معارك مكثفة في أوضاع متعددة: ديث ماتش، باتل رويال، زومبي والمزيد.",
    screenshots: ["💥", "🔫", "🎖️", "🚁"]
  },
  {
    id: 12,
    name: "Chess - Play & Learn",
    dev: "Chess.com",
    cat: "strategy",
    catLabel: "استراتيجية",
    icon: "♟️",
    color: "#27ae60",
    bg: "linear-gradient(135deg, #2c3e50 0%, #27ae60 100%)",
    rating: 4.8,
    downloads: "50م+",
    size: "35 MB",
    android: "5.0+",
    featured: false,
    tags: ["شطرنج", "ذكاء", "استراتيجية"],
    desc: "تعلم الشطرنج وتحسن مهاراتك! العب ضد الذكاء الاصطناعي أو منافسين حقيقيين من حول العالم. دروس تعليمية، ألغاز يومية، وبطولات.",
    screenshots: ["♟️", "🏆", "📈", "🧠"]
  }
];
